name: Terraform Plan

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Terraform init
        run: terraform -chdir=terraform init
      - name: Terraform plan
        run: terraform -chdir=terraform plan
